export const ALL_DLSU_PROGRAMS: string[] = [
  // Br. Andrew Gonzalez FSC College of Education (BAGCED)
  "Bachelor in Human Services",
  "Bachelor of Early Childhood Education",
  "Bachelor of Secondary Education",

  // Tañada-Diokno School of Law
  "Bachelor of Arts in Legal Studies and Sustainable Development",

  // College of Liberal Arts (CLA)
  "Bachelor of Arts in Behavioral Sciences",
  "Bachelor of Arts in Behavioral Sciences major in Organizational and Social Systems Development and Master of Arts in Behavioral Sciences",
  "Bachelor of Arts in Development Studies",
  "Bachelor of Arts in Development Studies and Bachelor of Science in Accountancy",
  "Bachelor of Arts in Development Studies and Bachelor of Science in Advertising Management",
  "Bachelor of Arts in Development Studies and Bachelor of Science in Applied Corporate Management",
  "Bachelor of Arts in Development Studies and Bachelor of Science in Business Management",
  "Bachelor of Arts in Development Studies and Bachelor of Science in Entrepreneurship",
  "Bachelor of Arts in Development Studies and Bachelor of Science in Legal Management",
  "Bachelor of Arts in Development Studies and Bachelor of Science in Management of Financial Institutions",
  "Bachelor of Arts in Development Studies and Bachelor of Science in Marketing Management",
  "Bachelor of Arts in History",
  "Bachelor of Arts in History and Bachelor of Science in Accountancy",
  "Bachelor of Arts in History and Bachelor of Science in Advertising Management",
  "Bachelor of Arts in History and Bachelor of Science in Applied Corporate Management",
  "Bachelor of Arts in History and Bachelor of Science in Business Management",
  "Bachelor of Arts in History and Bachelor of Science in Entrepreneurship",
  "Bachelor of Arts in History and Bachelor of Science in Legal Management",
  "Bachelor of Arts in History and Bachelor of Science in Management of Financial Institutions",
  "Bachelor of Arts in History and Bachelor of Science in Marketing Management",
  "Bachelor of Arts in International Studies",
  "Bachelor of Arts in Literature",
  "Bachelor of Arts in Literature major in Creative Writing",
  "Bachelor of Arts in Literature major in Literary and Cultural Studies",
  "Bachelor of Arts in Literature major in Literature Across the Professions",
  "Bachelor of Arts in Philippine Studies",
  "Bachelor of Arts in Philosophy and Artificial Intelligence",
  "Bachelor of Arts in Sociology",
  "Bachelor of Arts in Southeast Asian Studies",
  "Bachelor of Arts in Sports Studies",
  "Bachelor of Arts major in Communication Arts",
  "Bachelor of Arts major in Organizational Communication",
  "Bachelor of Arts major in Philosophy",
  "Bachelor of Arts major in Political Science",
  "Bachelor of Arts major in Psychology",
  "Bachelor of Science in Psychology",

  // Carlos L. Tui School of Economics (SOE)
  "Bachelor of Arts major in Economics",
  "Bachelor of Arts major in Economics and Bachelor of Science in Accountancy",
  "Bachelor of Arts major in Economics and Bachelor of Science in Advertising Management",
  "Bachelor of Arts major in Economics and Bachelor of Science in Applied Corporate Management",
  "Bachelor of Arts major in Economics and Bachelor of Science in Business Management",
  "Bachelor of Arts major in Economics and Bachelor of Science in Legal Management",
  "Bachelor of Arts major in Economics and Bachelor of Science in Management of Financial Institutions",
  "Bachelor of Arts major in Economics and Bachelor of Science in Marketing Management",
  "Bachelor of Science in Applied Economics",
  "Bachelor of Science in Applied Economics and Data Science",

  // Ramon V. del Rosario College of Business (RVRCOB)
  "Bachelor of Science in Accountancy",
  "Bachelor of Science in Advertising Management",
  "Bachelor of Science in Applied Corporate Management",
  "Bachelor of Science in Business Management",
  "Bachelor of Science in Business Management with specialization in Business Analytics",
  "Bachelor of Science in Entrepreneurship",
  "Bachelor of Science in Entrepreneurship Challenge Based Learning",
  "Bachelor of Science in Financial Engineering",
  "Bachelor of Science in Interdisciplinary Business Studies",
  "Bachelor of Science in Legal Management",
  "Bachelor of Science in Management Accounting with specialization in Business Analytics",
  "Bachelor of Science in Management of Financial Institutions",
  "Bachelor of Science in Marketing Management",

  // Gokongwei College of Engineering (GCOE)
  "Bachelor of Science in Aeronautical Engineering",
  "Bachelor of Science in Biomedical Engineering",
  "Bachelor of Science in Chemical Engineering",
  "Bachelor of Science in Civil Engineering",
  "Bachelor of Science in Computer Engineering",
  "Bachelor of Science in Electrical Engineering",
  "Bachelor of Science in Electronics Engineering",
  "Bachelor of Science in Industrial Engineering",
  "Bachelor of Science in Industrial Engineering with specialization in Data Analytics",
  "Bachelor of Science in Manufacturing and Robotics Engineering",
  "Bachelor of Science in Manufacturing Engineering and Management with specialization in Mechatronics and Robotics Engineering and Master of Science in Manufacturing Engineering",
  "Bachelor of Science in Mechanical Engineering",
  "Bachelor of Science in Mobility Engineering",

  // College of Science (COS)
  "Bachelor of Science in Animal Biology",
  "Bachelor of Science in Applied Physics",
  "Bachelor of Science in Biochemistry",
  "Bachelor of Science in Biology major in Medical Biology (Laguna)",
  "Bachelor of Science in Biology major in Medical Biology (Manila)",
  "Bachelor of Science in Biology major in Molecular Biology and Biotechnology",
  "Bachelor of Science in Biology major in Systematics and Ecology",
  "Bachelor of Science in Chemistry",
  "Bachelor of Science in Chemistry major in Food Science",
  "Bachelor of Science in Human Biology (Laguna)",
  "Bachelor of Science in Human Biology (Manila)",
  "Bachelor of Science in Mathematics with specialization in Business Applications",
  "Bachelor of Science in Physics",
  "Bachelor of Science in Premed Physics",
  "Bachelor of Science in Statistics major in Actuarial Science",

  // School of Innovation and Sustainability (SIS)
  "Bachelor of Science in Materials Science and Engineering",

  // College of Computer Studies (CCS)
  "Bachelor of Science in Computer Science",
  "Bachelor of Science in Data Science",
  "Bachelor of Science in Information Security",
  "Bachelor of Science in Information Systems",
  "Bachelor of Science in Information Technology",
  "Bachelor of Science in Interactive Entertainment major in Game Art and Design",
  "Bachelor of Science in Interactive Entertainment major in Game Development",

  "Other / Not Listed",
];